Target-template alignment
>P1;DDR1_HUMAN_D0
sequence:DDR1_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
------DFPRSRLRFKEKLGEGQFGEVHLCEVDSPQDLVSLDFPLNVRKGHPLLVAVKILRPDATKNARNDFLKEVKIMSRLKDPNIIRLLGVCVQDDPLCMITDYMENGDLNQFLSAHQLEDKAAEGAPGDGQAAQGPTISYPMLLHVAAQIASGMRYLATLNFVHRDLATRNCLVGENFTIKIADFGMSRNLYAGDYYRVQGRAVLPIRWMAWECILMGKFTTASDVWAFGVTLWEVLMLCRAQPFGQLTDEQVIENAGEFFRDQGRQVYLSRPPACPQGLYELMLRCWSRESEQRPPFSQLHRFLAE---------DALNTV*
>P1;SRC_CHICK_3DQW_A
structureX:SRC_CHICK_3DQW_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
LAKDAWEIPRESLRLEVKLGQGCFGEVWMGTWNGTTR-----------------VAIKTLKPGTM--SPEAFLQEAQVMKKLRHEKLVQLYAV-VSEEPIYIV-EYMSKGSLLDFL-----------------KGEMGKYLRLPQLVDMAAQIASGMAYVERMNYVHRDLRAANILVGENLVCKVADFGLARLIEDNETARQGAK--FPIKWTAPEAALYGRFTIKSDVWSFGILLTELTTKGRV-PYPGMVNREVLDQVERGYR-------MPCPPECPESLHDLMCQCWRKDPEERPTFEYLQAFLEDYFTSTEPQYQPGENL*
