Target-template alignment
>P1;DDR1_HUMAN_D0_PROTONATED
sequence:DDR1_HUMAN_D0_PROTONATED:FIRST:@:LAST :@:::-1.00:-1.00
--DFPRSRLRFKEKLGEGQFGEVHLCEVDSPQDLVSLDFPLNVRKGHPLLVAVKILRPDATKNARNDFLKEVKIMSRLKDPNIIRLLGVCVQDDPLCMITDYMENGDLNQFLSAHQLEDKAAEGAPGDGQAAQGPTISYPMLLHVAAQIASGMRYLATLNFVHRDLATRNCLVGENFTIKIADFGMSRNLYAGDYYRVQGRAVLPIRWMAWECILMGKFTTASDVWAFGVTLWEVLMLCRAQPFGQLTDEQVIENAGEFFRDQGRQVYLSRPPACPQGLYELMLRCWSRESEQRPPFSQLHRFLAE---------DALNTV*
>P1;SRC_CHICK_3U4W_A
structureX:SRC_CHICK_3U4W_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
AWEIPRESLRLEVKLGQGCFGEVWMGTWNGTTR-----------------VAIKTLKPGTM--SPEAFLQEAQVMKKLRHEKLVQLYAV-VSEEPIYIVTEYMSKGSLLDFL-----------------KGEMGKYLRLPQLVDMAAQIASGMAYVERMNYVHRDLRAANILVGENLVCKVADFGLARLIEDNEYTARQG-AKFPIKWTAPEAALYGRFTIKSDVWSFGILLTELTTKGRV-PYPGMVNREVLDQVERGYR-------MPCPPECPESLHDLMCQCWRKDPEERPTFEYLQAFLEDYFTSTEPQYQPGENL*
