Target-template alignment
>P1;DDR1_HUMAN_D0_PROTONATED
sequence:DDR1_HUMAN_D0_PROTONATED:FIRST:@:LAST :@:::-1.00:-1.00
-----DFPRSRLRFKEKLGEGQFGEVHLCEVDSPQDLVSLDFPLNVRKGHP-LLVAVKILRPDATKNARNDFLKEVKIMSRLKDPNIIRLLGVCVQDDPLCMITDYMENGDLNQFLSAHQLEDKAAEGAPGDGQAAQGPTISYPMLLHVAAQIASGMRYLATLNFVHRDLATRNCLVGENFTIKIADFGMSRNLYAGDYYRVQGRAVLPIRWMAWECILMGKFTTASDVWAFGVTLWEVLMLCRAQPFGQLTDEQVIENAGEFFRDQGRQVYLSRPPACPQGLYELMLRCWSRESEQRPPFSQLHRFLAED------------ALNTV*
>P1;IGF1R_HUMAN_1K3A_A
structureX:IGF1R_HUMAN_1K3A_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
VPDEWEVAREKITMSRELGQGSFG------------MVYEGVAKGVVKDEPETRVAIKTVNEAASMRERIEFLNEASVMKEFNCHHVVRLLGVVSQGQPTLVIMELMTRGDLKSYLRSLR---------------PEMPSLS--KMIQMAGEIADGMAYLNANKFVHRDLAARNCMVAEDFTVKIGDFGMTRDIETD---RKGGKGLLPVRWMSPESLKDGVFTTYSDVWSFGVVLWEIATLAE-QPYQGLSNEQVLR----FVMEGG---LLDKPDNCPD-MLELMRMCWQYNPKMRPSFLEIISSIKEEMEPGFREVSFYYSEENK*
