Target-template alignment
>P1;DDR1_HUMAN_D0
sequence:DDR1_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
-------DFPRSRLRFKEKLGEGQFGEVHLCEVDSPQDLVSLDFPLNVRKGHPLLVAVKILRPDATKNARNDFLKEVKIMSRLKDPNIIRLLGVCVQDDPLCMITDYMENGDLNQFLSAHQLEDKAAEGAPGDGQAAQGPTISYPMLLHVAAQIASGMRYLATLNFVHRDLATRNCLVGENFTIKIADFGMSRNLYAGDYYRVQGRAVLPIRWMAWECILMGKFTTASDVWAFGVTLWEVLMLCRAQPFGQLTDEQVIENAGEFFRDQGRQVYLSRPPACPQGLYELMLRCWSRESEQRPPFSQLHR-FLAEDALNTV*
>P1;ABL1_HUMAN_2G2I_A
structureX:ABL1_HUMAN_2G2I_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
SPNYDKWEMERTDITMKHKLGGGEVYE-------------------GVWKKYSLTVAVKTLKEDTME--VEEFLKEAAVMKEIKHPNLVQLLGVCTREPPFYIITEFMTYGNLLDYLRECNRQE-----------------VNAVVLLYMATQISSAMEYLEKKNFIHRDLAARNCLVGENHLVKVADFGLSR-LMTGDTYTAAG-AKFPIKWTAPESLAYNKFSIKSDVWAFGVLLWEIATY-GMSPYPGIDLSQVYELLEKDYR-------MERPEGCPEKVYELMRACWQWNPSDRPSFAEIHQAFETMFQESSI*
