Target-template alignment
>P1;DDR1_HUMAN_D0
sequence:DDR1_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
-------DF---------------------------------------------------------------------------PRSRLRFKE-----------------------------KLGEGQF-----------------------GEVH----LCEVDSPQ---------DLVSLDFPLNVRKGHPLL-------------VAVKILRPDATKNARNDFLKEVKIMSRLKDPNIIRLLGVCVQDDPLCMITDYMENGDLNQFLSAHQLEDKAAEGAPGDGQAAQGPTISYPMLLHVAAQIASGMRYLATLNFVHRDLATRNCLVGENFTIKIADFGMSRNLYAGDYYRVQGRAVLPIRWMAWECILMGKFTTASDVWAFGVTLWEVLMLCRAQPFGQLTDEQVIENAGEFFRDQGRQVYLSRPPACPQGLYELMLRCWSRESEQRPPFSQLHRFLAE--------DALNTV*
>P1;SRC_HUMAN_2SRC_A
structureX:SRC_HUMAN_2SRC_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
TTFVALYDYESRTETDLSFKKGERLQIVNNTEGDWWLAHSLSTGQTGYIPSNYVAPSDSIQAEEWYFGKITRRESERLLLNAENPRGTFLVRESETTKGAYCLSVSDFDNAKGLNVKHYKIRKLDSGGFYITSRTQFNSLQQLVAYYSKHADGLCHRLTTVCPTSKPQTQGLAKDAWEIPRESLRLEVKLGQGCFGEVWMGTWNGTTRVAIKTLKPGTM--SPEAFLQEAQVMKKLRHEKLVQLYAV-VSEEPIYIVTEYMSKGSLLDFL-----------------KGETGKYLRLPQLVDMAAQIASGMAYVERMNYVHRDLRAANILVGENLVCKVADFGLARLIEDNEYTARQG-AKFPIKWTAPEAALYGRFTIKSDVWSFGILLTELTTKGRV-PYPGMVNREVLDQVERGYR-------MPCPPECPESLHDLMCQCWRKEPEERPTFEYLQAFLEDYFTSTEPQQPGENL*
