Target-template alignment
>P1;DDR1_HUMAN_D0
sequence:DDR1_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
D------FPRSRLRFKEKLGEGQFGEVHLCEVDSPQDLVSLDFPLNVRKGHPLLVAVKILRPDATKNARNDFLKEVKIMSRLKDPNIIRLLGVCVQDDPLCMITDYMENGDLNQFLSAHQLEDKAAEGAPGDGQAAQGPTISYPMLLHVAAQIASGMRYLATLNFVHRDLATRNCLVGENFTIKIADFGMSRNLYAGDYYRVQGRAVLPIRWMAWECILMGKFTTASDVWAFGVTLWEVLMLCRAQPFGQLTDEQVIENAGEFFRDQGRQVYLSRPPACPQGLYELMLRCWSRESEQRPPFSQLH-RFLAEDALNTV---*
>P1;NTRK1_HUMAN_4GT5_A
structureX:NTRK1_HUMAN_4GT5_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
SDACVHHIKRRDIVLKWELGEGAFGKVFLAEC---HNLLP----------DKMLVAVKALK--ESESARQDFQREAELLTMLQHQHIVRFFGVCTEGRPLLMVFEYMRHGDLNRFLRSHGPDAKLGE------DVAPGP-LGLGQLLAVASQVAAGMVYLAGLHFVHRDLATRNCLVGQGLVVKIGDFGMSRDIYSTDYYRVGGRTMLPIRWMPPESILYRKFTTESDVWSFGVVLWEIFTYGK-QPWYQLSNTEAIDCI-----TQGRE--LERPRACPPEVYAIMRGCWQREPQQRHSIKDVHARLQALAQAPPVYLD*
