Target-template alignment
>P1;DDR1_HUMAN_D0_PROTONATED
sequence:DDR1_HUMAN_D0_PROTONATED:FIRST:@:LAST :@:::-1.00:-1.00
-------DFPRSRLRFKEKLGEGQFGEVHLCEVDSPQDLVSLDFPLNVRKGHP-LLVAVKILRPDATKNARNDFLKEVKIMSRLKDPNIIRLLGVCVQDDPLCMITDYMENGDLNQFLSAHQLEDKAAEGAPGDGQAAQGPTISYPMLLHVAAQIASGMRYLATLNFVHRDLATRNCLVGENFTIKIADFGMSRNLYAGDYYRVQGRAVLPIRWMAWECILMGKFTTASDVWAFGVTLWEVLMLCRAQPFGQLTDEQVIENAGEFFRDQGRQVYLSRPPACPQGLYELMLRCWSRESEQRPPFSQLHRFLAED------------ALNTV*
>P1;INSR_HUMAN_1IR3_A
structureX:INSR_HUMAN_1IR3_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
SVVPDEWEVSREKITLLRELGQGSFGMVY---EGNARDII---------KGEAETRVAVKTVNESASLRERIEFLNEASVMKGFTCHHVVRLLGVVSKGQPTLVVMELMAHGDLKSYLRSLRPE---AENNPGR------PPPTLQEMIQMAAEIADGMAYLNAKKFVHRDLAARNCMVAHDFTVKIGDFGMTRDIETD---RKGGKGLLPVRWMAPESLKDGVFTTSSDMWSFGVVLWEITSLAE-QPYQGLSNEQVLK----FVMDGG---YLDQPDNCPERVTDLMRMCWQFNPKMRPTFLEIVNLLKDDLHPSFPEVSFFHSEENK*
