Target-template alignment
>P1;DDR1_HUMAN_D0
sequence:DDR1_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
--------DFPRSRLRFKEKLGEGQFGEVHLCEVDSPQDLVSLDFPLNVRKGHPLLVAVKILRPDATKNARNDFLKEVKIMSRLKDPNIIRLLGVCVQDDPLCMITDYMENGDLNQFLSAHQLEDKAAEGAPGDGQAAQGPTISYPMLLHVAAQIASGMRYLATLNFVHRDLATRNCLVGENFTIKIADFGMSRNLYAGDYYRVQGRAVLPIRWMAWECILMGKFTTASDVWAFGVTLWEVLMLCRAQPFGQLTDEQVIENAGEFFRDQGRQVYLSRPPACPQGLYELMLRCWSRESEQRPPFSQLHRFLAEDALNTV*
>P1;MUSK_RAT_1LUF_A
structureX:MUSK_RAT_1LUF_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
LNPKLLSLEYPRNNIEYVRDIGEGAFGRVF--QARAP-GLLPYE-PFT-------MVAVKMLKEEASADMQADFQREAALMAEFDNPNIVKLLGVCAVGKPMCLLFEYMAYGDLNEFL-----------------RSMSPPPLSCAEQLCIARQVAAGMAYLSERKFVHRDLATRNCLVGENMVVKIADFGLSRNIYSADYYK----DAIPIRWMPPESIFYNRYTTESDVWAYGVVLWEIFSY-GLQPYYGMAHEEVI-----YYVRDGN--ILACPENCPLELYNLMRLCWSKLPADRPSFCSIHRILQRMC---E*
