Target-template alignment
>P1;DDR1_HUMAN_D0_PROTONATED
sequence:DDR1_HUMAN_D0_PROTONATED:FIRST:@:LAST :@:::-1.00:-1.00
DF---------------------------------------------------------------------------------PRSRLRFKE-----------------------------KLGEGQF-----------------------GEVH----LCEVDSPQ---------DLVSLDFPLNVRKGHPLL-------------VAVKILRPDATKNARNDFLKEVKIMSRLKDPNIIRLLGVCVQDDPLCMITDYMENGDLNQFLSAHQLEDKAAEGAPGDGQAAQGPTISYPMLLHVAAQIASGMRYLATLNFVHRDLATRNCLVGENFTIKIADFGMSRNLYAGDYYRVQGRAVLPIRWMAWECILMGKFTTASDVWAFGVTLWEVLMLCRAQPFGQLTDEQVIENAGEFFRDQGRQVYLSRPPACPQGLYELMLRCWSRESEQRPPFSQLHRFLAEDALNTV-----*
>P1;SRC_HUMAN_2H8H_A
structureX:SRC_HUMAN_2H8H_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
TFVALYDYESRTETDLSFKKGERLQIVNNTEGDWWLAHSLSTGQTGYIPSNYVAPSDSIQAEEWYFGKITRRESERLLLNAENPRGTFLVRESETTKGAYCLSVSDFDNAKGLNVKHYKIRKLDSGGFYITSRTQFNSLQQLVAYYSKHADGLCHRLTTVCPTSKPQTQGLAKDAWEIPRESLRLEVKLGQGCFGEVWMGTWNGTTRVAIKTLKPGTM--SPEAFLQEAQVMKKLRHEKLVQLYAV-VSEEPIYIVTEYMSKGSLLDFL-----------------KGETGKYLRLPQLVDMAAQIASGMAYVERMNYVHRDLRAANILVGENLVCKVADFGLARLIEDNEYTARQG-AKFPIKWTAPEAALYGRFTIKSDVWSFGILLTELTTKGRV-PYPGMVNREVLDQVERGYR-------MPCPPECPESLHDLMCQCWRKEPEERPTFEYLQAFL-EDYFTSTEPQQP*
