Target-template alignment
>P1;DDR1_HUMAN_D0
sequence:DDR1_HUMAN_D0:FIRST:@:LAST :@:::-1.00:-1.00
-------DFPRSRLRFKEKLGEGQFGEVHLCEVDSPQDLVSLDFPLNVRKGHPLLVAVKILRPDATKNARNDFLKEVKIMSRLKDPNIIRLLGVCVQDDPLCMITDYMENGDLNQFLSAHQLEDKAAEGAPGDGQAAQGPTISYPMLLHVAAQIASGMRYLATLNFVHRDLATRNCLVGENFTIKIADFGMSRNLYAGDYYRVQGRAVLPIRWMAWECILMGKFTTASDVWAFGVTLWEVLMLCRAQPFGQLTDEQVIENAGEFFRDQGRQVYLSRPPACPQGLYELMLRCWSRESEQRPPFSQLHRFL------------AEDALNTV*
>P1;ABL1_HUMAN_2F4J_A
structureX:ABL1_HUMAN_2F4J_A:FIRST:@:LAST : :undefined:undefined:-1.00:-1.00
SPNYDKWEMERTDITMKHKLGGGQYGEVYE----------------GVWKKYSLTVAVKTLKEDTME--VEEFLKEAAVMKEIKHPNLVQLLGVCTREPPFYIITEFMTYGNLLDYLRECNRQE-----------------VNAVVLLYMATQISSAMEYLEKKNFIHRDLAARNCLVGENHLVKVADFGLSR-LMTGDTYTAAG-AKFPIKWTAPESLAYNKFSIKSDVWAFGVLLWEIATY-GMSPYPGIDLSQVYELLEKDYR-------MERPEGCPEKVYELMRACWQWNPSDRPSFAEIHQAFETMFQESSISDEVEKELGKQ*
